package com.vlibrovs.litenotes.presentation.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF00696c)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF6ff6fa)
val md_theme_light_onPrimaryContainer = Color(0xFF002021)
val md_theme_light_secondary = Color(0xFF4a6363)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFcce8e8)
val md_theme_light_onSecondaryContainer = Color(0xFF041f20)
val md_theme_light_tertiary = Color(0xFF4d5f7c)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFd4e3ff)
val md_theme_light_onTertiaryContainer = Color(0xFF061c36)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFfafdfc)
val md_theme_light_onBackground = Color(0xFF191c1c)
val md_theme_light_surface = Color(0xFFfafdfc)
val md_theme_light_onSurface = Color(0xFF191c1c)
val md_theme_light_surfaceVariant = Color(0xFFdae4e4)
val md_theme_light_onSurfaceVariant = Color(0xFF3f4949)
val md_theme_light_outline = Color(0xFF6f7979)

// Extensions
val md_theme_light_primaryContainer_onClick = Color(0xff5CCBCE)
val md_theme_light_secondaryContainer_onClick = Color(0xffAAC2C2)
val md_theme_light_tertiaryContainer_onClick = Color(0xffB0BCD3)

val md_theme_dark_primary = Color(0xFF4cdadd)
val md_theme_dark_onPrimary = Color(0xFF003738)
val md_theme_dark_primaryContainer = Color(0xFF004f51)
val md_theme_dark_onPrimaryContainer = Color(0xFF6ff6fa)
val md_theme_dark_secondary = Color(0xFFb0cccc)
val md_theme_dark_onSecondary = Color(0xFF1b3435)
val md_theme_dark_secondaryContainer = Color(0xFF324b4c)
val md_theme_dark_onSecondaryContainer = Color(0xFFcce8e8)
val md_theme_dark_tertiary = Color(0xFFb4c7e9)
val md_theme_dark_onTertiary = Color(0xFF1e314c)
val md_theme_dark_tertiaryContainer = Color(0xFF354863)
val md_theme_dark_onTertiaryContainer = Color(0xFFd4e3ff)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191c1c)
val md_theme_dark_onBackground = Color(0xFFe0e3e2)
val md_theme_dark_surface = Color(0xFF191c1c)
val md_theme_dark_onSurface = Color(0xFFe0e3e2)
val md_theme_dark_surfaceVariant = Color(0xFF3f4949)
val md_theme_dark_onSurfaceVariant = Color(0xFFbec8c8)
val md_theme_dark_outline = Color(0xFF899393)

// Extensions
val md_theme_dark_primaryContainer_onClick = Color(0xff003738)
val md_theme_dark_secondaryContainer_onClick = Color(0xff253A3A)
val md_theme_dark_tertiaryContainer_onClick = Color(0xff233043)


